version: '3.8'

services:
  app:
    container_name: express-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=production
    restart: on-failure:5
