version: '3.8'

services:
  app:
    container_name: express-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/bioverse?schema=public
    volumes:
      - .:/app  # Monta o diretório atual no container
    working_dir: /app  # Define o diretório de trabalho no container
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    container_name: postgres-db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bioverse
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bioverse"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: